import { Button, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    width: 320px;
    height: 180px;
    no-frame: true;
    background: #059;

    // This property can be accessed and changed by our Rust code
    in-out property <string> message: "Hello, World!";

    VerticalBox {
        alignment: center;
        spacing: 20px;

        Text {
            text: root.message;
            font-size: 24px;
            horizontal-alignment: center;
        }
    }
}