import { Theme } from "theme.slint";
import { AppLayout } from "layouts/default.slint";

export component MainWindow inherits Window {
    title: "MP3 Player";
    width: 400px;
    height: 600px;
    background: Theme.base-100;

    // Expose these properties so main.rs can easily see and modify them
    in property <string> current-time <=> layout.time-string;
    in property <int> battery-level <=> layout.battery-level;
    in property <string> bluetooth-status <=> layout.bluetooth-status;
    in property <string> current-view <=> layout.view;

    layout := AppLayout {
        // Vue Prop Assignment
        view: "Now Playing"; 

        // Anything put here fills out the @children slot!
        VerticalLayout {
            padding: Theme.space-md;
            alignment: center;
            
            Text {
                text: "Your MP3 Player Content Goes Here";
                horizontal-alignment: center;
                color: Theme.base-content;
            }
        }
    }
}