import { Theme } from "theme.slint";
import { Button } from "std-widgets.slint";
import { CustomCard } from "components/card.slint";

export component MainWindow inherits Window {
    width: 400px;
    height: 300px;
    
    // Define a dynamic property for the text
    in property <string> my_text: "Hello, Slint!";

    VerticalLayout {
        alignment: center;
        spacing: 20px;

        CustomCard {
            title: "Card One";
            highlight: false;
            
            Text { text: "This is body text injected into the card."; }
        }

        Text {
            text: root.my_text;
            color: Theme.primary;
            font-size: 24px;
            horizontal-alignment: center;
        }

        Button {
            text: "Click Me";
            clicked => {
                // Call the custom Rust callback
                root.button_clicked();
            }
        }
    }
    
    // Define the signal that Rust will listen to
    pure callback button_clicked();
}